name: "SonarCloud"

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 0

    - name: Cache Cake-Tools
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      with:
        path: tools
        key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

    - name: Cache SonarCloud packages
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    - name: Get Java 11
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
      with:
        java-version: "11"
        java-package: jre
        distribution: zulu

    - uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT: "nils-org_Topshelf.LightCore"
        SONAR_ORG: "nils-org"
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:"sonar.login=${{ env.SONAR_TOKEN }}" /d:"sonar.host.url=https://sonarcloud.io"
        .\build.ps1
        .\.sonar\scanner\dotnet-sonarscanner end /d:"sonar.login=${{ env.SONAR_TOKEN }}"
